import json
from pathlib import Path
from typing import Dict


INPUT_FILE = "templates/asm-to-awaf-example.json"
OUTPUT_FILE = "templates/migrated-awaf-policy.json"


def load_json(path: str) -> Dict:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def convert_asm_to_awaf(data: Dict) -> Dict:
    """
    Very simplified example of converting an ASM-style structure
    into an AWAF-style policy document.

    In real projects this mapping is much more complex and depends
    on platform version, features used, etc.
    """
    asm_policy = data.get("asmPolicy", {})
    awaf_target = data.get("awafTarget", {})

    # Base AWAF structure
    awaf_policy = {
        "policy": {
            "name": awaf_target.get("name", "Migrated-AWAF-Policy"),
            "enforcementMode": awaf_target.get("enforcementMode", "blocking"),
            "template": {
                "name": "POLICY_TEMPLATE_RAPID_DEPLOYMENT"
            },
            "blockingSettings": {
                "violations": []
            },
            "signatureSettings": {
                "signatureStaging": True
            },
            "description": awaf_target.get(
                "notes",
                "Example migrated policy generated by asm_to_awaf_converter.py"
            ),
        }
    }

    # Copy basic violations and flip to blocking if needed
    asm_violations = (
        asm_policy.get("blockingSettings", {}).get("violations", [])
    )

    for v in asm_violations:
        name = v.get("name")
        if not name:
            continue

        awaf_policy["policy"]["blockingSettings"]["violations"].append(
            {
                "name": name,
                "alarm": True,
                # In a real migration you might use rules/logic here
                "block": True,
            }
        )

    return awaf_policy


def save_json(path: str, data: Dict) -> None:
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)
    print(f"Written AWAF policy to: {path}")


def main() -> None:
    if not Path(INPUT_FILE).exists():
        print(f"Input file not found: {INPUT_FILE}")
        return

    print(f"Loading ASM example from: {INPUT_FILE}")
    data = load_json(INPUT_FILE)

    awaf_policy = convert_asm_to_awaf(data)
    save_json(OUTPUT_FILE, awaf_policy)


if __name__ == "__main__":
    main()
